---
name: Jenkins Security Scan

on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  security-scan:
    uses: jenkins-infra/jenkins-security-scan/.github/workflows/jenkins-security-scan.yaml@v2
